subject: "[Nextflow KR] {event_name} 모임 안내 ({dday})"

body: |
  안녕하세요, Nextflow 한국어 커뮤니티입니다.

  {event_name} 모임을 안내드립니다.

  - 일시: {dday}
  - 온라인 미팅 링크: {meeting_url}
  - 설문조사: {survey_url}

  많은 참여 부탁드립니다!

  ---
  Nextflow 한국어 커뮤니티
  https://www.youtube.com/@WorkflowLanguage
